# GitHub Pages + jekyll-theme-hamilton
# https://github.com/ngzhio/jekyll-theme-hamilton


baseurl: ""
url: "https://seishiroono.github.io"

title: Seishiro Ono
author: "Seishiro Ono"
email: "s-ono@g.ecc.u-tokyo.ac.jp"
google_scholar: "https://scholar.google.co.jp/citations?user=TNFITl4AAAAJ&hl=en"
#description: "A minimal and beautiful site built with Hamilton."

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: ngzhio/jekyll-theme-hamilton

# コメント（Disqus）を使う場合は shortname を設定
# disqus: your-disqus-shortname


# オプション
lang: en
paginate: 10
date_format: "%Y-%m-%d"
#subscribe: true

