# GitHub Pages + jekyll-theme-hamilton
# https://github.com/ngzhio/jekyll-theme-hamilton


baseurl: ""
url: "https://seishiroono.github.io"

title: Seishiro Ono
author: "Seishiro Ono"
email: "s-ono@g.ecc.u-tokyo.ac.jp"
google_scholar: "https://scholar.google.co.jp/citations?user=TNFITl4AAAAJ&hl=en"
orcid: "https://orcid.org/0000-0002-4908-2612"
#description: "A minimal and beautiful site built with Hamilton."

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar

scholar:
  source: ./_bibliography
  bibliography: references.bib
  sort_by: year
  order: descending
  style: apa
  csl: _csl/apa-author-given-family-full.csl
  locale: en
  bibliography_template: '{{ reference }}{% if entry.url %} <a href="{{ entry.url | escape }}" target="_blank" rel="noopener noreferrer">[link]</a>{% endif %}'

remote_theme: ngzhio/jekyll-theme-hamilton


# オプション
lang: en
paginate: 10
date_format: "%Y-%m-%d"
#subscribe: true
